#!/bin/bash

# init Kubernetes cluster
sudo kubeadm init --ignore-preflight-errors=all --control-plane-endpoint "$1:6443"

# prepare config
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config

# configure Pod network plugin
kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
