#!/bin/bash

sudo apt update

# install Docker dependencies and runtime
sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
apt-cache policy docker-ce
sudo apt install -y docker-ce

# run docker without sudo
sudo usermod -aG docker ubuntu

# install git and golang
sudo apt install -y git golang-go

# configure cri-docker due to Kubernetes 1.24 no longer supporting Docker runtime
git clone https://github.com/Mirantis/cri-dockerd.git
cd ~/cri-dockerd
mkdir bin
cd src && go get && go build -o ../bin/cri-dockerd
cd ~/cri-dockerd
mkdir -p /usr/local/bin
sudo install -o root -g root -m 0755 bin/cri-dockerd /usr/local/bin/cri-dockerd
sudo cp -a packaging/systemd/* /etc/systemd/system
sudo sed -i -e 's,/usr/bin/cri-dockerd,/usr/local/bin/cri-dockerd,' /etc/systemd/system/cri-docker.service

# enable IP forwarding
sudo bash -c "echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf"
sudo sysctl -p

# add Kubernetes repository
curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add
sudo apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"

sudo apt update

# install Kubernetes components
sudo apt install -y kubeadm kubectl kubelet

# update cgroupdriver
echo '{"exec-opts": ["native.cgroupdriver=systemd"]}' | sudo tee /etc/cri-docker/daemon.json
echo '{"exec-opts": ["native.cgroupdriver=systemd"]}' | sudo tee /etc/docker/daemon.json
sudo systemctl daemon-reload
sudo systemctl enable cri-docker.service
sudo systemctl enable docker
sudo systemctl enable --now cri-docker.socket
sudo systemctl restart docker
